# Generated by Django 5.1.2 on 2025-07-12 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0121_internalclient_code'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(choices=[('free', 'Free Trial'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='internalclient',
            name='billing_mode',
            field=models.CharField(choices=[('PRE', 'Prepaid'), ('POS', 'Postpaid')], default='PRE', max_length=15),
        ),
        migrations.AlterField(
            model_name='internalclient',
            name='code',
            field=models.CharField(default='IN', help_text='Country ISO code', max_length=15),
        ),
        migrations.CreateModel(
            name='ClientCreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_added', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_expired_at', models.DateTimeField(blank=True, help_text='Validity expired date', null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credits', models.PositiveSmallIntegerField(default=0)),
                ('transaction_type', models.CharField(blank=True, choices=[('purchase', 'Credit Purchase'), ('usage', 'Interview Usage'), ('refund', 'Refund'), ('manual', 'Admin Added')], max_length=15)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transaction', to='dashboard.clientcreditwallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditTopUpPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The original amount of the bill without any taxes or adjustments', max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, help_text='The total amount received including any applicable taxes', max_digits=10)),
                ('payment_link_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('payment_link_url', models.URLField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('SUC', 'Success'), ('FLD', 'Failed'), ('UDP', 'User Dropped'), ('CNL', 'Cancelled'), ('VOD', 'Void'), ('PED', 'Pending'), ('INA', 'Inactive')], default='PED', max_length=15)),
                ('link_status', models.CharField(blank=True, choices=[('PAID', 'Paid'), ('PRT', 'Partially Paid'), ('EXP', 'Expired'), ('CNL', 'Cancelled')], max_length=15, null=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('link_expired_time', models.DateTimeField()),
                ('cf_link_id', models.CharField(max_length=100, unique=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(max_length=254)),
                ('meta_data', models.JSONField(default=dict)),
                ('credit_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='dashboard.creditpackage')),
                ('credit_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='dashboard.clientcredittransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditPackagePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, help_text='Country ISO Code', max_length=15)),
                ('currency', models.CharField(default='INR', max_length=15)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('extra_credits', models.PositiveIntegerField(default=0)),
                ('validity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='dashboard.creditpackage')),
            ],
            options={
                'unique_together': {('package', 'country')},
            },
        ),
    ]
