# Generated by Django 5.1.2 on 2025-07-12 15:24

import dashboard.Models.Finance
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0122_creditpackage_internalclient_billing_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcreditwallet',
            name='credit_plan_type',
            field=models.CharField(choices=[('free', 'Free Trial'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientcreditwallet',
            name='credit_expired_at',
            field=models.DateTimeField(default=dashboard.Models.Finance.default_credit_expiry, help_text='Validity expired date'),
        ),
    ]
