# Generated by Django 5.1.2 on 2025-07-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0123_clientcreditwallet_credit_plan_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcreditwallet',
            name='balance',
        ),
        migrations.AddField(
            model_name='clientcreditwallet',
            name='total_credits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcreditwallet',
            name='total_added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientcreditwallet',
            name='total_spend',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
