# Generated by Django 5.1.2 on 2025-07-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0125_agreement_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcredittransaction',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clientcredittransaction',
            name='status',
            field=models.CharField(choices=[('SUC', 'Success'), ('FLD', 'Failed'), ('PRC', 'Processing')], default='SUC', max_length=15),
        ),
        migrations.AddField(
            model_name='clientcreditwallet',
            name='total_refunded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
