# Generated by Django 5.1.2 on 2025-07-18 07:08

from django.db import migrations


def modify_code_field_structure(apps, schema_editor):
    InternalClient = apps.get_model("dashboard", "InternalClient")
    InternalClient.objects.filter(code="INR").update(code="IN")


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0127_auto_populate_creditpackage_descriptions"),
    ]

    operations = [
        migrations.RunPython(modify_code_field_structure),
    ]
