# Generated by Django 5.1.2 on 2025-07-18 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0128_modify_internal_client_code_field_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcreditwallet',
            name='credit_plan_type',
        ),
        migrations.AddField(
            model_name='clientcreditwallet',
            name='pricing_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.creditpackagepricing'),
        ),
    ]
