# Generated by Django 5.1.2 on 2025-07-18 08:32

from django.db import migrations


def set_default_pricing_plan(apps, schema_editor):
    Wallet = apps.get_model("dashboard", "ClientCreditWallet")
    Pricing = apps.get_model("dashboard", "CreditPackagePricing")

    def get_default_plan(country_code):
        try:
            default_plan = Pricing.objects.get(
                package__name="free", country=country_code
            )
        except Pricing.DoesNotExist:
            default_plan = None

        return default_plan

    wallets = Wallet.objects.filter(pricing_plan__isnull=True)
    for wallet in wallets:
        wallet.pricing_plan = get_default_plan(wallet.client.internal_client.code)
        wallet.save()

        if not wallet.pricing_plan:
            print(
                f"Warning: No pricing plan found for country {wallet.client.internal_client.code} for wallet {wallet.id}"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0129_remove_clientcreditwallet_credit_plan_type_and_more"),
    ]

    operations = [
        migrations.RunPython(set_default_pricing_plan),
    ]
