# Generated by Django 5.1.2 on 2025-07-19 12:21

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0130_populate_default_pricing_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpointofcontact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
