# Generated by Django 5.1.2 on 2025-07-20 05:07

from django.db import migrations, models


def migrate_strength_to_stream(apps, schema_editor):
    InternalInterviewer = apps.get_model("dashboard", "InternalInterviewer")
    Stream = apps.get_model("dashboard", "Stream")

    for interviewer in InternalInterviewer.objects.all():
        strength_value = getattr(interviewer, "strength", None)
        if strength_value:
            stream_obj, _ = Stream.objects.get_or_create(name=strength_value)
            interviewer.stream.add(stream_obj)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0133_migrate_job_name_to_jobrole"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=155, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="internalinterviewer",
            name="stream",
            field=models.ManyToManyField(
                blank=True, related_name="interviewers", to="dashboard.stream"
            ),
        ),
        migrations.RunPython(migrate_strength_to_stream),
        migrations.RemoveField(
            model_name="internalinterviewer",
            name="assigned_domains",
        ),
        migrations.RemoveField(
            model_name="internalinterviewer",
            name="strength",
        ),
    ]
