# Generated by Django 5.1.2 on 2025-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0134_stream_remove_internalinterviewer_assigned_domains_and_more",
        ),
    ]

    operations = [
        # Step 1: Add temp field to store old text values
        migrations.AddField(
            model_name="candidate",
            name="specialization_temp",
            field=models.CharField(max_length=155, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="specialization_temp",
            field=models.CharField(max_length=155, null=True, blank=True),
        ),
        # Step 2: Copy data from old CharField to temp field using SQL
        migrations.RunSQL(
            sql="""
                UPDATE dashboard_candidate SET specialization_temp = specialization;
                UPDATE dashboard_job SET specialization_temp = specialization;
            """,
            reverse_sql="""
                UPDATE dashboard_candidate SET specialization_temp = NULL;
                UPDATE dashboard_job SET specialization_temp = NULL;
            """,
        ),
    ]
