# Generated by Django 5.1.2 on 2025-07-20 07:28

import django.db.models.deletion
from django.db import migrations, models


def migrate_specialization_text_to_stream_fk(apps, schema_editor):
    Stream = apps.get_model("dashboard", "Stream")
    Candidate = apps.get_model("dashboard", "Candidate")
    Job = apps.get_model("dashboard", "Job")

    for candidate in Candidate.objects.all():
        specialization_str = getattr(candidate, "specialization_temp", None)
        if specialization_str:
            stream, _ = Stream.objects.get_or_create(name=specialization_str)
            candidate.specialization = stream
            candidate.save(update_fields=["specialization"])

    for job in Job.objects.all():
        specialization_str = getattr(job, "specialization_temp", None)
        if specialization_str:
            stream, _ = Stream.objects.get_or_create(name=specialization_str)
            job.specialization = stream
            job.save(update_fields=["specialization"])


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0135_adding_specliation_content_specialization_temp"),
    ]

    operations = [
        # # Step 1: Remove old CharField
        migrations.RemoveField(
            model_name="candidate",
            name="specialization",
        ),
        migrations.RemoveField(
            model_name="job",
            name="specialization",
        ),
        # Step 2: Create new FK field with same name
        migrations.AddField(
            model_name="candidate",
            name="specialization",
            field=models.ForeignKey(
                to="dashboard.stream",
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="specialization",
            field=models.ForeignKey(
                to="dashboard.stream",
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                null=True,
                blank=True,
            ),
        ),
        # Step 3: Fill new FK from temp field using get_or_create
        migrations.RunPython(migrate_specialization_text_to_stream_fk),
        # Step 4: Cleanup temp field
        migrations.RemoveField(
            model_name="candidate",
            name="specialization_temp",
        ),
        migrations.RemoveField(
            model_name="job",
            name="specialization_temp",
        ),
    ]
