# Generated by Django 5.1.2 on 2025-07-21 17:27

from django.db import migrations
from common import constants
from hiringdogbackend.utils import get_display_name


def migrate_job_role_db_value_to_display_name(apps, schema_editor):
    JobRole = apps.get_model("dashboard", "JobRole")

    job_roles = JobRole.objects.all()
    for job_role in job_roles:
        job_role.name = get_display_name(job_role.name, constants.ROLE_CHOICES)
    JobRole.objects.bulk_update(job_roles, ["name"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0136_remove_specialization_charfield_and_add_specialization_foreignkey_field_also_add_the_existing_content",
        ),
    ]

    operations = [migrations.RunPython(migrate_job_role_db_value_to_display_name)]
