CURRENCIES = {
    "USD": {"name": "United States Dollar", "symbol": "$"},
    "EUR": {"name": "Euro", "symbol": "€"},
    "JPY": {"name": "Japanese Yen", "symbol": "¥"},
    "GBP": {"name": "British Pound Sterling", "symbol": "£"},
    "AUD": {"name": "Australian Dollar", "symbol": "A$"},
    "CAD": {"name": "Canadian Dollar", "symbol": "CA$"},
    "CHF": {"name": "Swiss Franc", "symbol": "₣"},
    "CNY": {"name": "Chinese Yuan", "symbol": "¥"},
    "HKD": {"name": "Hong Kong Dollar", "symbol": "HK$"},
    "NZD": {"name": "New Zealand Dollar", "symbol": "NZ$"},
    "SGD": {"name": "Singapore Dollar", "symbol": "S$"},
    "SEK": {"name": "Swedish Krona", "symbol": "Kr"},
    "KRW": {"name": "South Korean Won", "symbol": "₩"},
    "NOK": {"name": "Norwegian Krone", "symbol": "Kr"},
    "INR": {"name": "Indian Rupee", "symbol": "₹"},
    "TWD": {"name": "New Taiwan Dollar", "symbol": "NT$"},
    "RUB": {"name": "Russian Ruble", "symbol": "₽"},
    "MXN": {"name": "Mexican Peso", "symbol": "Mex$"},
    "BRL": {"name": "Brazilian Real", "symbol": "R$"},
    "ILS": {"name": "Israeli New Shekel", "symbol": "₪"},
    "IDR": {"name": "Indonesian Rupiah", "symbol": "Rp"},
    "AED": {"name": "United Arab Emirates Dirham", "symbol": "AED"},  # Formerly 'د.إ'
    "SAR": {"name": "Saudi Riyal", "symbol": "SAR"},  # Formerly '﷼'
}

COUNTRY_DETAILS = {
    "IN": {"name": "India", "currency": "INR"},
    "US": {"name": "United States", "currency": "USD"},
}

ROLE_CHOICES = (
    ("SDE_I", "SDE-I"),
    ("SDE_II", "SDE-II"),
    ("SDE_III", "SDE-III"),
    ("PE", "Principal Engineer"),
    ("EM", "Engineering Manager"),
    ("TL", "Technical Lead"),
    ("VPE", "VP Engineering"),
    ("DOE", "Director of Engineering"),
    ("DE", "DevOps Engineer"),
    ("SR_DE", "Senior DevOps Engineer"),
    ("LD_DE", "Lead DevOps Engineer"),
    ("SDET", "SDET"),
    ("SR_SDET", "Sr. SDET"),
    ("MGR_SDET", "Manager-SDET"),
    ("DIR_SDET", "Director-SDET"),
    ("MLS", "ML Scientist"),
    ("SR_MLS", "Sr. ML Scientist"),
    ("LD_MLS", "Lead ML Scientist"),
    ("P_MLS", "Principal ML Scientist"),
    ("DEE", "Data Engineer"),
    ("SR_DEE", "Sr. Data Engineer"),
    ("LD_DEE", "Lead Data Engineer"),
    ("P_DEE", "Principal Data Engineer"),
    ("SEM", "Senior Engineering Manager"),
    ("SPM", "Senior Principal Engineer"),
    ("STL", "Senior Technical Lead"),
    ("AVPE", "AVP Engineer"),
    ("SDE", "Senior Director Of Engineering"),
    ("SM_SDET", "Senior Manager SDET"),
    ("SP_MLS", "Senior Principal ML Scientist"),
    ("SL_DEE", "Senior Lead Data Engineer"),
    ("SP_DEE", "Senior Principal Data Engineer"),
    ("IN", "Intern"),
    ("AR", "Architecht"),
    ("SA", "Senior Architect"),
    ("PA", "Principal Architect"),
    ("QAE", "QA Engineer"),
    ("RS_II", "Research Scientist II"),
)

STRENGTH_CHOICES = (
    ("frontend", "Frontend"),
    ("backend", "Backend"),
    ("fullstack", "Fullstack"),
    ("aiml", "AI/ML"),
    ("devops", "DevOps"),
    ("data_engineer", "Data Engineering"),
    ("testing", "Testing/QA"),
    ("android", "Android"),
    ("ios", "iOS"),
    ("mobile", "Mobile (Android + iOS)"),
    ("flutter", "Flutter"),
    ("database", "Database"),
    ("cloud", "Cloud"),
    ("mobile_flutter", "Mobile (Flutter)"),
    ("mobile_react_native", "Mobile (React Native)"),
)
