name: Auto Deploy to MIG (Image-Based)
on:
  push:
    branches: [main]
env:
  PROJECT_ID: dynamic-now-438707-c1
  MIG_NAME: hiringdog-mig
  ZONE: asia-south1-b

jobs:
  gce-image-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/568722140219/locations/global/workloadIdentityPools/github-pool/providers/github'
        service_account: 'github-actions@dynamic-now-438707-c1.iam.gserviceaccount.com'
        
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2  # Updated version
      with:
        project_id: dynamic-now-438707-c1
        
    - name: Setup Packer
      uses: hashicorp/setup-packer@main
      
    - name: Build Custom Image
      run: |
        # Fix: Create shorter, valid image name
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
        IMAGE_NAME="hiringdog-$(date +%y%m%d%H%M%S)-${SHORT_SHA}"
        
        echo "Building image: $IMAGE_NAME"
        packer init .
        packer build \
          -var "project_id=$PROJECT_ID" \
          -var "image_name=$IMAGE_NAME" \
          -var "app_version=${{ github.sha }}" \
          packer-template.pkr.hcl
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        
    - name: Create new Instance Template
      run: |
        TEMPLATE_NAME=hiringdog-template-$(date +%y%m%d%H%M%S)
        gcloud compute instance-templates create $TEMPLATE_NAME \
          --machine-type=e2-medium \
          --image=$IMAGE_NAME \
          --tags=http-server,https-server \
          --metadata=startup-script='#!/bin/bash
            systemctl start hiringdog
            systemctl start nginx
            sleep 15
            curl -f http://localhost/health || exit 1
          '  # Fixed: Added missing closing quote
        echo "TEMPLATE_NAME=$TEMPLATE_NAME" >> $GITHUB_ENV
        
    - name: Update MIG with new template
      run: |
        gcloud compute instance-groups managed set-instance-template $MIG_NAME \
          --template=$TEMPLATE_NAME \
          --zone=$ZONE
          
    - name: Rolling Update MIG
      run: |
        gcloud compute instance-groups managed rolling-action start-update $MIG_NAME \
          --version=template=$TEMPLATE_NAME \
          --zone=$ZONE \
          --max-surge=1 \
          --max-unavailable=0
          
    - name: Wait for Rollout
      run: |
        gcloud compute instance-groups managed wait-until $MIG_NAME \
          --version-target-reached \
          --zone=$ZONE \
          --timeout=900
          
    - name: Verify Deployment
      run: |
        gcloud compute instance-groups managed list-instances $MIG_NAME \
          --zone=$ZONE \
          --format="table(instance,status,instanceStatus)"
          
    - name: Cleanup Old Images
      run: |
        gcloud compute images list \
          --filter="family=hiringdog-app" \
          --format="value(name)" \
          --sort-by="~creationTimestamp" \
          | tail -n +6 \
          | xargs -r -I {} gcloud compute images delete {} --quiet
