name: Auto Deploy to MIG (Image-Based)
on:
  push:
    branches: [script-sh]
env:
  PROJECT_ID: dynamic-now-438707-c1
  MIG_NAME: hiringdog-mig
  ZONE: asia-south1-b
  TEMPLATE_NAME: vm1-template-3

jobs:
  gce-image-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/568722140219/locations/global/workloadIdentityPools/github-pool/providers/github'
        service_account: 'github-actions@dynamic-now-438707-c1.iam.gserviceaccount.com'
        
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: dynamic-now-438707-c1
        

    - name: Check if MIG exists and create if needed
      run: |
        # Check if MIG exists
        if ! gcloud compute instance-groups managed describe $MIG_NAME --zone=$ZONE --quiet >/dev/null 2>&1; then
          echo "MIG $MIG_NAME does not exist. Creating it..."
          
          # Create the MIG (NO HEALTH CHECK)
          gcloud compute instance-groups managed create $MIG_NAME \
            --base-instance-name=hiringdog \
            --size=1 \
            --template=$TEMPLATE_NAME \
            --zone=$ZONE
          
          # Configure auto-scaling
          gcloud compute instance-groups managed set-autoscaling $MIG_NAME \
            --zone=$ZONE \
            --max-num-replicas=3 \
            --min-num-replicas=1 \
            --target-cpu-utilization=0.60
          
          echo "MIG created successfully!"
        else
          echo "MIG $MIG_NAME already exists. Proceeding with update..."
        fi
        
    - name: Update MIG with new template
      run: |
        gcloud compute instance-groups managed set-instance-template $MIG_NAME \
          --template=$TEMPLATE_NAME \
          --zone=$ZONE
              
    - name: Verify Deployment
      run: |
        INSTANCES=$(gcloud compute instance-groups managed list-instances $MIG_NAME --zone=$ZONE --format="value(instance)")
        echo "Deployed instances:"
        echo "$INSTANCES"
        # Optionally test HTTP response or SSH into an instance for smoke test
        
          
    
